# Generated by Django 4.2.11 on 2024-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demnde_devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('tel', models.CharField(default='', max_length=64)),
                ('email', models.CharField(default='', max_length=64)),
                ('pays', models.CharField(default='', max_length=64)),
                ('objet', models.CharField(default=64, max_length=64)),
                ('msg', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
